
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.analizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHEN = 12;
  public static final int SHOW = 14;
  public static final int LIT_INT = 56;
  public static final int POWER = 40;
  public static final int MULT = 36;
  public static final int CHAR = 23;
  public static final int LEFT_ARRAY = 32;
  public static final int LIT_FLOAT = 57;
  public static final int BLOCK_END = 26;
  public static final int GREATER = 47;
  public static final int INT = 20;
  public static final int LESS = 46;
  public static final int MINUS = 35;
  public static final int FOR = 13;
  public static final int NOT = 52;
  public static final int AND = 50;
  public static final int ENDL = 19;
  public static final int SEMICOLON = 31;
  public static final int RIGHT_ARRAY = 33;
  public static final int DECIDE = 7;
  public static final int BLOCK_START = 25;
  public static final int COAL = 6;
  public static final int OR = 51;
  public static final int BOOL = 22;
  public static final int COMMA = 29;
  public static final int GET = 15;
  public static final int NAVIDAD = 5;
  public static final int INC = 41;
  public static final int DIV = 37;
  public static final int LOOP = 10;
  public static final int PLUS = 34;
  public static final int EXIT = 11;
  public static final int ASSIGN = 43;
  public static final int OF = 8;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int DIV_INT = 38;
  public static final int error = 1;
  public static final int LIT_STRING = 54;
  public static final int LIT_CHAR = 55;
  public static final int MOD = 39;
  public static final int BREAK = 17;
  public static final int WORLD = 2;
  public static final int ARROW = 30;
  public static final int ELSE = 18;
  public static final int NOT_EQ = 45;
  public static final int LESS_EQ = 48;
  public static final int FLOAT = 21;
  public static final int END = 9;
  public static final int LIT_BOOL = 58;
  public static final int STRING = 24;
  public static final int LOCAL = 3;
  public static final int PAREN_CLOSE = 28;
  public static final int DEC = 42;
  public static final int GIFT = 4;
  public static final int PAREN_OPEN = 27;
  public static final int IDENTIFIER = 53;
  public static final int GREATER_EQ = 49;
  public static final int EQ_EQ = 44;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WORLD",
  "LOCAL",
  "GIFT",
  "NAVIDAD",
  "COAL",
  "DECIDE",
  "OF",
  "END",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "SHOW",
  "GET",
  "RETURN",
  "BREAK",
  "ELSE",
  "ENDL",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "BLOCK_START",
  "BLOCK_END",
  "PAREN_OPEN",
  "PAREN_CLOSE",
  "COMMA",
  "ARROW",
  "SEMICOLON",
  "LEFT_ARRAY",
  "RIGHT_ARRAY",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "DIV_INT",
  "MOD",
  "POWER",
  "INC",
  "DEC",
  "ASSIGN",
  "EQ_EQ",
  "NOT_EQ",
  "LESS",
  "GREATER",
  "LESS_EQ",
  "GREATER_EQ",
  "AND",
  "OR",
  "NOT",
  "IDENTIFIER",
  "LIT_STRING",
  "LIT_CHAR",
  "LIT_INT",
  "LIT_FLOAT",
  "LIT_BOOL"
  };
}

