/*
 * This source file was generated by the Gradle 'init' task
 */
package org.Lexer;

public final class App {
    private App() {

    }

    public static void main(String[] args) {
        Node test = new Node("Pepe");
        Node hijo1 = new Node("Pollo");
        Node hijo2 = new Node("Pollo2");
        Node hijo3 = new Node("Pollo3");

        hijo3.setChild(hijo2);
        test.setChild(hijo1);
        test.setChild(hijo2);
        test.setChild(hijo3);

        System.out.print(test);
    }
}
